apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  labels:
    app: webhook
    chart: webhook-v0.1.0
    heritage: Tiller
    release: cert-manager
  name: cert-manager-webhook-webhook-tls
  namespace: default
spec:
  dnsNames:
  - cert-manager-webhook
  - cert-manager-webhook.default
  - cert-manager-webhook.default.svc
  duration: 8760h
  issuerRef:
    name: cert-manager-webhook-ca
  secretName: cert-manager-webhook-webhook-tls
