apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: cert-manager
    release: cert-manager
  name: cert-manager
rules:
- apiGroups:
  - certmanager.k8s.io
  resources:
  - certificates
  - certificates/finalizers
  - issuers
  - clusterissuers
  - orders
  - orders/finalizers
  - challenges
  - challenges/finalizers
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - events
  - services
  - pods
  verbs:
  - '*'
- apiGroups:
  - extensions
  resources:
  - ingresses
  - ingresses/finalizers
  verbs:
  - '*'
