apiVersion: apps/v1
kind: Deployment
metadata:
  name: sserve
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sserve
  template:
    metadata:
      labels:
        name: sserve
    spec:
      containers:
      - name: sgetserve
        image: quay.io/established/sget
        imagePullPolicy: Always
        env:
        - name: PUBLIC_REPO
          value: "https://github.com/philips/releases-test"
        - name: PRIVATE_REPO
          value: "https://github.com/philips/sget-certificates"
        command: ["/sget"]
        args: ["server", "$(PUBLIC_REPO)", "$(PRIVATE_REPO)"]
