apiVersion: v1
kind: Service
metadata:
  labels:
    app: ipfs
    release: ipfs
  name: ipfs-ipfs
spec:
  ports:
  - name: api
    port: 5001
    protocol: TCP
    targetPort: 5001
  - name: gateway
    port: 8080
    targetPort: 8080
  selector:
    app: ipfs
    release: ipfs
  type: ClusterIP
